### ISSUE TITLE
[Discussion]: Patch LoadFolders To-Do

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#3076]
Just various xml patch and housekeeping-related things to do in the near future:
## To Do
- [x] Replace outdated `PatchOperationTest` and `<success>` usages using `match`, where sensible.
- [x] Extract `Defs`.
- [ ] Steamline JDS Star Wars - Armory patch.
- [ ] ~~Load time benchmarking.~~
- [x] Resolve lingering PatchOpAdd `Defs`.
- [x] Implement Bioferrite and Deadlife shells on projectile sheet.
